version: "3.6"
services:
  ui:
    depends_on:
      - app
    container_name: cui
    image: gcr.io/coinos-326717/github.com/tokenocean/cozmos:staging
    restart: on-failure
  app:
    depends_on:
      - hbp
    container_name: ca
    image: gcr.io/coinos-326717/github.com/tokenocean/cozmos-server:staging
    restart: on-failure
    environment:
      APP_URL: "${APP_URL}"
      CLOUDFLARE_TOKEN: "${CLOUDFLARE_TOKEN}"
      CLOUDFLARE_ZONE: "${CLOUDFLARE_ZONE}"
      COINOS_TOKEN: "${COINOS_TOKEN}"
      COINOS_URL: "${COINOS_URL}"
      DOMAIN: "${DOMAIN}"
      HASURA_JWT: "${HASURA_GRAPHQL_JWT_SECRET}"
      HASURA_SECRET: "${HASURA_GRAPHQL_ADMIN_SECRET}"
      HASURA_URL: "${HASURA_URL}"
      HBP_URL: "${HBP_URL}"
      IPFS_URL: "${IPFS_URL}"
      IPFS_WEB_URL: "${IPFS_WEB_URL}"
      LIQUID_ELECTRS_URL: "${LIQUID_ELECTRS_URL}"
      NFT_STORAGE_TOKEN: "${NFT_STORAGE_TOKEN}"
      NODE_ENV: "production"
      SERVER_URL: "${SERVER_URL}"
      SIGNING_SERVER_MNEMONIC: "${SIGNING_SERVER_MNEMONIC}"
      SMTP_HOST: "${SMTP_HOST}"
      SMTP_PASS: "${SMTP_PASS}"
      SMTP_PORT: "${SMTP_PORT}"
      SMTP_SENDER: "${SMTP_SENDER}"
      SMTP_USER: "${SMTP_USER}"
      RPCHOST: "${RPCHOST}"
      RPCPORT: "${RPCPORT}"
      RPCUSER: "${RPCUSER}"
      RPCPASS: "${RPCPASS}"
      RPCWALLET: "${RPCWALLET}"
    volumes:
      - ./custom:/opt/src/hasura/app/custom
      - ${STORAGE_DIR}:/export
  hasura:
    container_name: ch
    image: hasura/graphql-engine:v2.13.0-beta.1
    restart: always
    volumes:
      - ./migrations:/hasura-migrations
      - ./metadata:/hasura-metadata
      - ./seeds:/hasura-seeds
    environment:
      HASURA_GRAPHQL_DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/cozmos"
      HASURA_GRAPHQL_ADMIN_SECRET: "${HASURA_GRAPHQL_ADMIN_SECRET}"
      HASURA_GRAPHQL_JWT_SECRET: "${HASURA_GRAPHQL_JWT_SECRET}"
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: "anonymous"
  hbp:
    container_name: chb
    image: nhost/hasura-backend-plus:v2.4.0
    depends_on:
      - hasura
    environment:
      SERVER_URL: "${SERVER_URL}"
      HASURA_ENDPOINT: "${HASURA_URL}/v1/graphql"
      HASURA_GRAPHQL_ADMIN_SECRET: "${HASURA_GRAPHQL_ADMIN_SECRET}"
      JWT_ALGORITHM: "${JWT_ALGORITHM}"
      JWT_KEY: "${JWT_KEY}"
      AUTO_MIGRATE: "true"
      STORAGE_ENABLE: "false"
      MAX_REQUESTS: 10000
      LOST_PASSWORD_ENABLE: "true"
      EMAILS_ENABLE: "true"
      SMTP_HOST: "${SMTP_HOST}"
      SMTP_PORT: "${SMTP_PORT}"
      SMTP_USER: "${SMTP_USER}"
      SMTP_PASS: "${SMTP_PASS}"
      SMTP_SENDER: "${SMTP_SENDER}"
      AUTO_ACTIVATE_NEW_USERS: "false"
      VERIFY_EMAILS: "true"
    volumes:
      - ./custom:/app/custom
networks: 
  default: 
    name: coinos
    external: true
